[package]
name = "synpixel/catppuccin"
description = "Catppuccin for Roblox and Luau"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["palette.luau", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
